# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_sel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(578, 401)
        self.spinBox_num_set_row = QtWidgets.QSpinBox(Dialog)
        self.spinBox_num_set_row.setGeometry(QtCore.QRect(90, 100, 50, 22))
        self.spinBox_num_set_row.setObjectName("spinBox_num_set_row")
        self.spinBox_num_set_col = QtWidgets.QSpinBox(Dialog)
        self.spinBox_num_set_col.setGeometry(QtCore.QRect(90, 130, 50, 22))
        self.spinBox_num_set_col.setObjectName("spinBox_num_set_col")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(220, 90, 257, 188))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.comboBox_data_se3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_data_se3.setObjectName("comboBox_data_se3")
        self.comboBox_data_se3.addItem("")
        self.comboBox_data_se3.setItemText(0, "")
        self.gridLayout.addWidget(self.comboBox_data_se3, 4, 0, 1, 1)
        self.comboBox_data_sel2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_data_sel2.setObjectName("comboBox_data_sel2")
        self.gridLayout.addWidget(self.comboBox_data_sel2, 2, 0, 1, 1)
        self.spinBox_data2_row = QtWidgets.QSpinBox(self.widget)
        self.spinBox_data2_row.setObjectName("spinBox_data2_row")
        self.gridLayout.addWidget(self.spinBox_data2_row, 2, 2, 1, 1)
        self.spinBox_data2_col = QtWidgets.QSpinBox(self.widget)
        self.spinBox_data2_col.setObjectName("spinBox_data2_col")
        self.gridLayout.addWidget(self.spinBox_data2_col, 2, 4, 1, 1)
        self.spinBox_data3_col = QtWidgets.QSpinBox(self.widget)
        self.spinBox_data3_col.setObjectName("spinBox_data3_col")
        self.gridLayout.addWidget(self.spinBox_data3_col, 4, 4, 1, 1)
        self.spinBox_data1_row = QtWidgets.QSpinBox(self.widget)
        self.spinBox_data1_row.setObjectName("spinBox_data1_row")
        self.gridLayout.addWidget(self.spinBox_data1_row, 0, 2, 1, 1)
        self.spinBox_data4_col = QtWidgets.QSpinBox(self.widget)
        self.spinBox_data4_col.setObjectName("spinBox_data4_col")
        self.gridLayout.addWidget(self.spinBox_data4_col, 6, 4, 1, 1)
        self.comboBox_data_se1 = QtWidgets.QComboBox(self.widget)
        self.comboBox_data_se1.setObjectName("comboBox_data_se1")
        self.comboBox_data_se1.addItem("")
        self.comboBox_data_se1.setItemText(0, "")
        self.gridLayout.addWidget(self.comboBox_data_se1, 0, 0, 1, 1)
        self.spinBox_data1_col = QtWidgets.QSpinBox(self.widget)
        self.spinBox_data1_col.setObjectName("spinBox_data1_col")
        self.gridLayout.addWidget(self.spinBox_data1_col, 0, 4, 1, 1)
        self.spinBox_data3_row = QtWidgets.QSpinBox(self.widget)
        self.spinBox_data3_row.setObjectName("spinBox_data3_row")
        self.gridLayout.addWidget(self.spinBox_data3_row, 4, 2, 1, 1)
        self.comboBox_data_se4 = QtWidgets.QComboBox(self.widget)
        self.comboBox_data_se4.setObjectName("comboBox_data_se4")
        self.comboBox_data_se4.addItem("")
        self.comboBox_data_se4.setItemText(0, "")
        self.gridLayout.addWidget(self.comboBox_data_se4, 6, 0, 1, 1)
        self.spinBox_data4_row = QtWidgets.QSpinBox(self.widget)
        self.spinBox_data4_row.setObjectName("spinBox_data4_row")
        self.gridLayout.addWidget(self.spinBox_data4_row, 6, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
